cat:
	fsharpc --nologo -a readNWrite.fs 
	fsharpc -r readNWrite.dll cat.fsx
tac:
	fsharpc --nologo -a readNWrite.fs 
	fsharpc -r readNWrite.dll tac.fsx
cl:
	fsharpc --nologo -a readNWrite.fs 
	fsharpc -r readNWrite.dll countLinks.fsx